### PR TITLE
Add isgood function

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by rdeits** [comment]
thanks!

**Comment by rdeits** [comment]
I'm confused about the nightly failures on OSX but not linux, but I'm willing to ignore that for now.

**Comment by rdeits** [comment]
Maybe it was this: https://github.com/JuliaLang/julia/pull/23876

**Comment by tkoolen** [comment]
https://github.com/JuliaLang/julia/issues/23846#issuecomment-333824290.

**Pull request merged**
