### PR TITLE
Add `LCMType`: semi-automatic way to encode and decode LCM message types

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by tkoolen** [comment]
So this currently doesn't test against an implementation in another language. I was wondering: do you think it's feasible to test against the C implementation instead of the Python implementation?

**Comment by rdeits** [comment]
Alternatively, what if we just generate some LCM messages in Python ahead of time, serialize them, and store the bytes? Then we can test LCMCore by deserializing those bytes and verifying that all the fields have the expected values. It means checking in some binary data, but probably less than 1 or 2 kB.

**Comment by rdeits** [comment]
(and we can test serialization by re-serializing the decoded data and verifying that the bytes are exactly the same)

**Comment by tkoolen** [comment]
That's a great idea.

**Comment by tkoolen** [comment]
Added the tests you recommended (which caught a bug where I was also encoding and decoding fingerprints for `LCMType` fields of `LCMType`s, d'oh).

**Comment by rdeits** [comment]
This is really excellent, thanks!

**Comment by tkoolen** [comment]
Thank you!

**Pull request merged**
